### PR TITLE
[Github #805] proxy calls via the worker

### LINKED ISSUE #805: Worker proxy calls should be independent from the Server
We had an instance of an infinite loop in a Sync sync which crashed the Server due to proxy calls. 

In general, the worker should probably scale independently from the server. 

——-

Sdk could have a local proxy method that uses a proxy service

### PR DESCRIPTION
**Pull request by khaliqgant**
## Describe your changes
Moves code around to allow script proxy calls to be distributed by the worker

## Issue ticket number and link
Resolves #805 

## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [x] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is: n/a
- [ ] I added analytics, otherwise the reason is: n/a

## Manual Test Checklist
- [x] Tested that dry run works as expected
- [x] Tested that a deployed sync work as expect
- [x] Tested that a regular HTTP proxy call works as expected
- [x] Tested that a node sdk proxy call works as expected
- [x] Tested that an API that throws an error is the same as was previous
- [x] Tested that a paginate helper call still works

### CODE REVIEW

File: packages/shared/lib/sdk/sync.ts [hunk 1]
```diff
@@ -254,7 +255,31 @@ export class NangoAction {
...
+            config.connectionId = this.connectionId;
+        }
+
+        if (!config.providerConfigKey && this.providerConfigKey) {
+            config.providerConfigKey = this.providerConfigKey;
+        }
+
+        return (
+            this.dryRun ? this.nango.proxy(config) : proxyService.routeOrConfigure(config, { ...internalConfig, connection: connection as Connection })
+        ) as Promise<AxiosResponse<T>>;
```
Comment (TBonnin) [inline packages/shared/lib/sdk/sync.ts]: could we remove one code code branch like this ```

        if (!config.connectionId && this.connectionId) {
            config.connectionId = this.connectionId;
        }

        if (!config.providerConfigKey && this.providerConfigKey) {
            config.providerConfigKey = this.providerConfigKey;
        }

        if (this.dryRun) {
             return this.nango.proxy(config) 
        } else {
            const connection = await this.nango.getConnection(this.providerConfigKey as string, this.connectionId as string);
            return proxyService.routeOrConfigure(config, { ...internalConfig, connection: connection });
        }
```

**Review by TBonnin — APPROVED** [review]

File: packages/shared/lib/sdk/sync.ts (hunk 1 above)
Comment (khaliqgant) [reply packages/shared/lib/sdk/sync.ts]: Yup! Done with https://github.com/NangoHQ/nango/pull/1358/commits/162bdbec21494da977384111c0183458326ee462
