### PR TITLE
[Github #1276] fix create call

### LINKED ISSUE #1276: Fix additional argument for auth.create call

### PR DESCRIPTION
**Pull request by khaliqgant**
Resolves #1276 

- Export `RecordMetadata` in case users want to use that type for the `getRecords` response
- Small tweak to the info icon to be the correct size
image

### CODE REVIEW

File: packages/frontend/lib/index.ts [hunk 1]
```diff
@@ -56,7 +56,8 @@ export default class Nango {
         this.publicKey = config.publicKey;
 
         if (!config.publicKey) {
-            throw new Error('You must specify a public key (cf. documentation).');
+            const error = new AuthError('You must specify a public key (cf. documentation).', 'missingPublicKey');
+            throw error;
```
Comment (TBonnin) [inline packages/frontend/lib/index.ts]:
```suggestion
            throw new AuthError('You must specify a public key (cf. documentation).', 'missingPublicKey');;
```

File: packages/frontend/lib/index.ts [hunk 2]
```diff
@@ -66,11 +67,12 @@ export default class Nango {
             const websocketUrl = new URL(config.websocketsPath, baseUrl);
             this.websocketsBaseUrl = websocketUrl.toString().replace('https://', 'wss://').replace('http://', 'ws://');
         } catch (err) {
-            throw new Error(`Invalid URL provided for the Nango host: ${this.hostBaseUrl}`);
+            const error = new AuthError('Invalid URL provided for the Nango host.', 'invalidHostUrl');
+            throw error;
```
Comment (TBonnin) [inline packages/frontend/lib/index.ts]:
```suggestion
            throw new AuthError('Invalid URL provided for the Nango host.', 'invalidHostUrl');
```

File: packages/frontend/lib/index.ts [hunk 3]
```diff
@@ -106,7 +108,8 @@ export default class Nango {
         try {
             new URL(url);
         } catch (err) {
-            throw new Error(`Could not construct valid Nango URL based on provided parameters: ${url}`);
+            const error = new AuthError('Invalid URL provided for the Nango host.', 'invalidHostUrl');
+            throw error;
```
Comment (TBonnin) [inline packages/frontend/lib/index.ts]:
```suggestion
            throw new AuthError('Invalid URL provided for the Nango host.', 'invalidHostUrl');
```

File: packages/frontend/lib/index.ts [hunk 4]
```diff
@@ -183,12 +186,13 @@ export default class Nango {
...
         connectionConfigWithCredentials: ConnectionConfig,
-        connectionConfig: ConnectionConfig
+        connectionConfig?: ConnectionConfig
     ): Promise<AuthResult> {
         const { params: credentials } = connectionConfigWithCredentials as ConnectionConfig;
 
         if (!credentials) {
-            throw new Error('You must specify credentials.');
+            const authError = new AuthError('You must specify credentials.', 'missingCredentials');
+            throw authError;
```
Comment (TBonnin) [inline packages/frontend/lib/index.ts]:
```suggestion
            throw new AuthError('You must specify credentials.', 'missingCredentials');
```

File: packages/frontend/lib/index.ts [hunk 5]
```diff
@@ -214,7 +218,8 @@ export default class Nango {
         if ('username' in credentials || 'password' in credentials) {
             const basicCredentials = credentials as BasicApiCredentials;
             if (!basicCredentials.username) {
-                throw new Error('You must specify a username.');
+                const authError = new AuthError('You must specify a username.', 'missingUsername');
+                throw authError;
```
Comment (TBonnin) [inline packages/frontend/lib/index.ts]:
```suggestion
                throw new AuthError('You must specify a username.', 'missingUsername');
```

**Review by TBonnin — APPROVED** [review]
